### ISSUE TITLE
Errors aren't handled in the `catch`

### ISSUE THREAD

**Issue by lynnaloo** [alabeduarte/feedparser-promised#1]
The "Not a feed" error coming from feedparser isn't being handled with the example code. Instead of handling this gracefully, it crashes the server.

**Comment by lynnaloo** [comment]
The PR I referenced should fix this issue.

**Comment by alabeduarte** [comment]
I believe its fixed with this commit 58d1f14

This will be available already on version 1.1.0. Please let me know if its working well for you then I'll close this issue.

Best!
