### ISSUE TITLE
Parsing XML attributes

### ISSUE THREAD

**Issue by Ziker22** [alabeduarte/feedparser-promised#10]
Hi,
Is there a way to get custom xml attributes when promise is resolved ?
example
```
<item segment="home">
<title>blah</title>
<link>
blabla.com
</link>
</item>
```

I want to parse segment="home" part

thx in advance

**Comment by alabeduarte** [comment]
Hi @Ziker22 

You could get your custom attribute from `'rss@'` key, example:

```javascript
feedparser.parse(url).then( (items) => {
    items.forEach( (item) => {
      const customAttribute = item['rss:@'];
      console.log(`custom attribute: ${customAttribute}`);
      console.log(`custom attribute called 'segment': ${customAttribute.segment}`);
    });
  })
```

I hope it helps for what you're looking for.

Cheers!

**Comment by alabeduarte** [comment]
Hi @Ziker22 

Do you have any feedback about this issue? Can I close it?

Cheers

**Comment by alabeduarte** [comment]
Hi @Ziker22 

I'll close this issue for now but please let me know if you have further questions and we re-open it, is that ok?

Cheers
