### ISSUE TITLE
App crashes in IE 11

### ISSUE THREAD

**Issue by Ziker22** [alabeduarte/feedparser-promised#11]
Hi,
After adding your lib it works perfectly and thank you for that :)
Only problem is that is crashes on IE11 with error
SCRIPT1002: Syntax error
File: bundle.js, Line: 117906, Column: 19

Error is pointing on this code 

```
module.exports = class FeedParserPromised {
	  static parse (options) {
	    return new Promise( (resolve, reject) => {
	      const items = [];
	      const feedparser = new FeedParser();

	      feedparser.on('error', (err) => { reject(err); });

	      feedparser.on('readable', () => {
	        let item;

	        while(item = feedparser.read()) { items.push(item); }

	        return items;
	      });
```
Also this WARNING is displayed after webpack build

`WARNING in ./~/ajv/dist/ajv.bundle.js
Critical dependencies:
1:476-483 This seems to be a pre-built javascript file. Though this is possible,
 it's not recommended. Try to require the original source to get better results.

 @ ./~/ajv/dist/ajv.bundle.js 1:476-483`

Any ideas how to solve this would be appreciated

thx in advance

**Comment by alabeduarte** [comment]
Hi @Ziker22 

Do you know exactly which line of the code snippet that you shared refers to this browser issue? 

I'm wondering if it's regarding some [compatibility issue between ES6 and IE 11](https://kangax.github.io/compat-table/es6/).

Cheers

**Comment by Ziker22** [comment]
Thx for the reply.
It is actually the very first line with
module.exports = class FeedParserPromised

**Comment by alabeduarte** [comment]
Hi @Ziker22 

Looks like [IE11 doesn't support ES6 classes](https://stackoverflow.com/questions/37194202/ie11-gives-script1002-error-when-defining-class-in-javascript).

Maybe with [babel](https://babeljs.io/) we could make it work. I'll work on this as soon as I can, but feel free to send a pull request whenever you want.

Cheers

**Comment by alabeduarte** [comment]
Hi @Ziker22 

Looks like [IE11 doesn't support ES6 classes](https://stackoverflow.com/questions/37194202/ie11-gives-script1002-error-when-defining-class-in-javascript).

Are you using babel?

Cheers

**Comment by Ziker22** [comment]
Hey @alabeduarte  ,
I played little bit with it and wasnt able to make this work.
But i just copy pasted feedParserPromised.js into my src folder and plugged it in and it work.
The thing is that now feedParserPromised.js is being transpiled with babel.
So this leads me to conclusion that one of us has webpack setup wrong .

**Comment by alabeduarte** [comment]
Hi @Ziker22 
Would you mind to share your webpack/babel configuration file?

Thanks!

**Comment by alabeduarte** [comment]
Hi, @Ziker22 

I'll close this issue for now but we can open the discussion again if you will. I'm guessing that it could be an issue with webpack or babel configuration which is not considering your libraries in the process of transpiling.

Cheers!
