### ISSUE TITLE
Parser crashes on this valid RSS feed

### ISSUE THREAD

**Issue by dsl101** [alabeduarte/feedparser-promised#13]
I originally raised this on the feedparser project, as I'd presumed it was something there. But @danmactough said it looks like this feed is being served gzipped, and the wrapper needs to unzip that before passing it on. [This is the feed URL which breaks](http://www.arctic-council.org/index.php/en/?format=feed&type=rss) and the `curl` response looks like this:

	curl -i "http://www.arctic-council.org/index.php/en/?format=feed&type=rss"

	HTTP/1.1 200 OK
	Server: nginx
	Date: Fri, 28 Apr 2017 18:30:09 GMT
	Content-Type: application/rss+xml; charset=utf-8
	Transfer-Encoding: chunked
	Connection: keep-alive
	Content-Encoding: gzip
	Expires: Wed, 17 Aug 2005 00:00:00 GMT
	ETag: http://www.arctic-council.org/index.php/en/?format=feed&type=rss
	Cache-Control: no-cache
	Pragma: no-cache
	Set-Cookie: 9b25b2ceec56fcde5bd7ce6373ce6f76=bp2mueorpmsfdn3kmvucgkqof4; path=/; HttpOnly
	Last-Modified: Fri, 28 Apr 2017 18:27:09 GMT
	Host-Header: 192fc2e7e50945beb8231a492d6a8024
	X-Proxy-Cache: MISS

Note the `Content-Encoding` header. I _believe_ all that's required is adding `gzip: true` to the `request()` call... See [here](https://github.com/request/request#examples) for why this isn't the default option.

**Comment by alabeduarte** [comment]
Hi @dsl101 

Thank you for open this issue, as `feedparser-promised` is compatible with `request` API, you can pass the gzip as an option. Follow the example below:

```javascript
const feedparser = require('feedparser-promised');

const options = {
  uri: 'http://www.arctic-council.org/index.php/en/?format=feed&type=rss',
  gzip: true
};

feedparser.parse(options).then( (items) => {
  items.forEach(item => console.log('title: ', item.title));
}).catch(error => console.log('error: ', error));
```
### Result:

>"title: Arctic Council Expert Groups"
>"title: The Arctic Council: A Forum for Peace and Cooperation"
>"title: Agreements"
>"title: Statements"

Please let me know if this is what you were looking for so then I can close this issue.

Cheers

**Comment by dsl101** [comment]
Gah! Of course! It's been so long since I looked at this app I'd forgotten
the request could be an object not just a plain URL.

I will fix it in the app. Many thanks,

David

**Comment by alabeduarte** [comment]
No worries, I'm here to help anytime!
