### ISSUE TITLE
The ES6 class syntax makes this unusable in ES5 projects

### ISSUE THREAD

**Issue by JReinhold** [alabeduarte/feedparser-promised#15]
I cannot use this library in a project that's not setup to transpile ES6 sources, because of the `class` syntax.

Most notably, the [create-react-app](https://github.com/facebookincubator/create-react-app/) boilerplate used by thousands of people, expects all dependencies to be ES5 when **building**. See https://github.com/facebookincubator/create-react-app/issues/2433#issuecomment-305461337 for an explanation.

I recommend adding a build step that uses babel to transpile the sources to ES5, and puts them in a /lib folder.

A quick try on [Try Babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code_lz=OQVwzgpgBGAuBOBLAxrYBuAUJ5B7AdnFPBAI4gREC8xZIiJAFMCeZWgJRZ6GxQBiECABMACgEN4keFBqt6TYADMhwgA6TpwLtgC2uYSAA2EAHQQAHmtzxYYWVGRHxYe4JESpEeKPi5diJDCUADemFAwsOKwKFAaXlCMuGoxBGAcoeERtLAg8PhQ-BAA7lC-_oEQjIkkYLhGAG4QADS0AFYQqBlUAHyZ2dk8RIiwELr2NADaALpYAxFDfCoi8dIORaXuYprejDpZA8vqO_CmBMzefvDArYyX3X0h7Z2wd_DwXFAAvvvzUEerbxnfDMEjiYTiABGJhuiQe_T-UBMfBGYywB3mxQAFogTIxUboHACTqYwcI9hkngSwKY1OAsfjRrpPl9sIicnkCtS5vMfui_vJ2KYAOYQV7JVKEDgYgbAi7vGywt4fWSPZ6oZUs6Xs2mINRVYleD4y7Jy4AQfDCJXwp4kXL5Wh1RpValankRPlZVlfdBAA) showed that the code was plug and play, and everything worked when pasting the transpiled code into the `feedparser-promised` module.

It looks like you tried to convert everything to es5 in this commit https://github.com/alabeduarte/feedparser-promised/commit/f8256d441ee80ae30463837759805d9b2a29cfb9 , but I don't think you succeed, maybe I'm reading the commit wrong.

I have [a fork of this for my personal usage](https://github.com/JReinhold/feedparser-promised) that fixes the issue, however I haven't tested it extensively, only with my own React project.
Let me know if you want a PR to this repo. If you see other solutions, please tell.

**Comment by alabeduarte** [comment]
Hi @JReinhold 

Thank you for open this issue. In the past, [`feedparser-promised-v1.1.1`](https://github.com/alabeduarte/feedparser-promised/tree/1.1.1) had support to ES5 features using babel and I removed for the sake of simplicity and I didn't receive any feedback regarding the need of having support for ES5.

Since now you need this support and seems you already know what needs to be done based on your needs, feel free to submit a PR, would be really appreciated!

Cheers
