### ISSUE TITLE
Unicode issue with Chinese Language.

### ISSUE THREAD

**Issue by shahidmau** [alabeduarte/feedparser-promised#20]
I am getting issue with Chinese text, I am able to fetch the data but Chinese text are broken. I am providing an example url.

http://www.chinanews.com/rss/scroll-news.xml

Kindly Check.

**Comment by shahidmau** [comment]
Kindly check this.
https://github.com/danmactough/node-feedparser/issues/62

**Comment by alabeduarte** [comment]
Hi @shahidmau 

I'm looking at this issue, sorry for the delay. In the meanwhile, have you tried different options of encoding as https://github.com/danmactough/node-feedparser/issues/62 suggests? If you perform a `curl` on your terminal can you get the right encoding?

```
curl http://www.chinanews.com/rss/scroll-news.xml
```

I'd try spin up a server and open the HTTP response in a browser just for checking. In the meanwhile, I'll investigate different options.

Cheers

**Comment by alabeduarte** [comment]
@shahidmau 

Looking at old issues I just found this: https://github.com/alabeduarte/feedparser-promised/issues/9#issuecomment-283830648

Could you try the script below and see if you have different results?

Install `iconv-lite`:
```
npm install iconv-lite
```
Run this code below:

```javascript
const feedparser = require('feedparser-promised');
const iconv = require('iconv-lite');
const encode = 'iso-8859-1'; // put your encode here

feedparser.parse('http://www.chinanews.com/rss/scroll-news.xml').then(items => {
  items.map(item => iconv.decode(new Buffer(item.title), encode)
    .forEach(console.log);
}).catch(console.log);
```

**Comment by alabeduarte** [comment]
Hi @shahidmau 

Any feedback regarding this issue? I'll close it for now but let me know if think still worth to investigate it.

Cheers
