### ISSUE TITLE
Is it possible to remove unwanted characters?

### ISSUE THREAD

**Issue by theasteve** [alabeduarte/feedparser-promised#27]
I'm currently working on parsing RSS Feeds. I find this package to work great with `namespaces` which have been pitfalls in other packages. Currently I'm making use of the option `normalize: true`. I wonder if it would be possible to remove some of the characters in the response.

For example to clean the response a bit
```  
'rss:link':
   { '@': {},
     '#':
      'http://www.nycgovparks.org/events/2019/06/08/astoria-park-carnival1' },
  'rss:description':
   { '@': {},
     '#':
      '<p>Date: June 8, 2019</p><p><p>Join the Central Astoria Local Development Coalition for its annual Astoria Park at the Astoria Park Parking Lot. The Carnival will feature games, food, rides, and fun for the entire family. We look forward to seeing you there!</p>\n\n<p>The Carnival will take place on Wednesday, June 5 through Sunday, June 9. </p>\n\n<p><strong>Carnival Hours</strong></p>\n\n<ul>\n\t<li>Wednesday, June 5 and Thursday, June 6: 4:00 p.m. - 10:00 p.m.</li>\n\t<li>Friday, June 7: 4:00 p.m. - 11:00 p.m.</li>\n\t<li>Saturday, June 8: Noon to midnight</li>\n\t<li>Sunday, June 9: Noon to 11:00 p.m.</li>\n</ul></p><p>Start time: 12:00 pm</p><p>End time: 11:59 pm</p><p>Contact phone: (718) 728-7820</p><p>Location: Parking Lot (in Astoria Park)</p>' },
  'event:parkids': { '@': {}, '#': 'Q004' },
  'event:parknames': { '@': {}, '#': 'Astoria Park' },
  'event:startdate': { '@': {}, '#': '2019-06-08' },
  'event:enddate': { '@': {}, '#': '2019-06-08' },
  'event:starttime': { '@': {}, '#': '12:00 pm' },
  'event:endtime': { '@': {}, '#': '11:59 pm' },
  'event:contact_phone': { '@': {}, '#': '(718) 728-7820' },
  'event:location': { '@': {}, '#': 'Parking Lot (in Astoria Park)' }
```
Would it be possible to remove `'@'`, `{}` thus cleaning the output of the parsing? Is there an option that will accomplish this? So it can look something like ` 'event:parkids':  'Q004' `

**Comment by alabeduarte** [comment]
Hi @theasteve 

Sorry for taking so long to reply. The `feedparser-promised` library only delegates the work to https://github.com/danmactough/node-feedparser

Have you checked if this is possible with the newest version of `node-feedparser`?

**Comment by theasteve** [comment]
@alabeduarte thanks for getting back to me. I was able to fix it by creating a method that parses those characters out. https://github.com/CityOfNewYork/nyco-rss-2-json

**Comment by alabeduarte** [comment]
Thank you @theasteve 

I'm glad you worked that out!
