### ISSUE TITLE
Can't load feedparser-promised - broken package?

### ISSUE THREAD

**Issue by dsl101** [alabeduarte/feedparser-promised#3]
I'm converting a load of old callback-based code to nice shiny promises, and was hoping this module would make things really easy. But I'm stuck at the first step. I've run `npm i --save feedparser-promised` and put `var FeedParser = require('feedparser-promised);` at the top of the code. But I get this:

```
[nodemon] starting `node app.js`
module.js:336
    throw err;
          ^
Error: Cannot find module './lib/feedParserPromised'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/node/classifier/node_modules/feedparser-promised/index.js:1:88)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
```

and indeed there is no `/lib` folder there. I tried running `make` in the `node_modules/feedparser-promised` folder, but apart from a couple of warnings, it didn't seem to change anything. In case you're interested, the warnings were:

```
$ make
npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN cannot run in wd feedparser-promised@1.0.2 babel -d lib src/ (wd=/node/classifier/node_modules/feedparser-promised)
```

and then a bunch of modules with dependencies. But still no `/lib` folder... Am I'm missing something? I re-read the README several times...

**Comment by alabeduarte** [comment]
Hi @dsl101 

This is a generated directory by the project and I did some change that introduced this bug.

Please try to use version `1.0.1` for while and I'll fix this right away on the next version `1.0.3`.

Sorry by the inconvenience.

**Comment by alabeduarte** [comment]
@dsl101 

I have fixed this issue. Could you try the version `1.0.3` please?

Thanks

**Comment by dsl101** [comment]
Fab - many thanks. `1.0.3` working fine. And _so_ much nicer than feedparser :)

**Comment by alabeduarte** [comment]
As it uses `feedparser` behind the scenes, let's consider both of them pretty nice!

Thank you!

**Comment by dsl101** [comment]
Of course. One day, everything will just be promises though :)
