### ISSUE TITLE
Recent update broke passing options to underlying feedparser

### ISSUE THREAD

**Issue by dsl101** [alabeduarte/feedparser-promised#5]
Ref [my old ticket](https://github.com/alabeduarte/feedparser-promised/issues/4), after updating the code, it seems the underlying feedparser is no longer getting the options object passed in. Indeed, this looks to be the case in the source code, as it is instantiated as `const feedparser = new FeedParser();` rather than `const feedparser = new FeedParser(options);`.

I couldn't exactly follow the change that led to this, but is it possible to put options support back in?

Many thanks!

**Comment by alabeduarte** [comment]
Hi @dsl101 

Do you have some code example with the actual and expected result?

On [that](https://github.com/alabeduarte/feedparser-promised/issues/4) issue I only added a few unit tests and changed the README.md, nothing was changed at the production code.

Thanks!

**Comment by dsl101** [comment]
Well, only that I'm passing an options object to the underlying feedparser which is no longer working, and when I hacked a `console.log(options)` _into_ the underlying feedparser library, it was an empty object. Adding that line above back into feedparser-promised brought the expected behaviour back.

BTW - I wasn't suggesting changes from my old ticket were the cause - just that I couldn't follow the most recent changes to see where the problem first surfaced.

**Comment by dsl101** [comment]
BTW - I wasn't suggesting changes from my old ticket were the cause - just that I couldn't follow the most recent changes to see where the problem first surfaced.

**Comment by alabeduarte** [comment]
So it seems that you're trying to instantiate FeedParser which at this moment wasn't design to be used that way. The options is passing through a static method `parse`.

Try use `FeedParser.parse(options)` instead of `new FeedParser(options)`.

I'm assuming we're talking about `feedparser-promised` instead of [node-parser](https://github.com/danmactough/node-feedparser).

You can copy and paste this code below (same as [last issue](#4))) and try it out through this uri: https://runkit.com/npm/feedparser-promised

``` javascript
var FeedParser = require('feedparser-promised');

const tryout = (options) => {
  FeedParser.parse(options).then( (items) => {
    console.log(items.length);

    const allTitles = items.map( (item) => { return item.title; });
    console.log(allTitles);
  }).catch( (err) => {
    console.log('feedParserPromised error caught: ', err);
  });
};

const uri = 'http://www.europlanet-eu.org/feed/'

tryout({ uri: uri, timeout: 1 });
/*
expected output:
feedParserPromised error caught:  { [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: true }
*/

tryout({ uri: uri, timeout: 3000 });
/*
expected output:
10
[ 'ESOF 2016 – What do you think a comet smells like?',
  'Juno public event: Tuesday, 5 July 2016, Athens',
  'Liquid water in Ceres’s past',
  'Counting Down to Jupiter',
  'Mission Juno : University of Liège goes into orbit at Jupiter',
  'European involvement in the Juno mission',
  'Scientists come to Schloss Seggau to discuss Rosetta’s comet',
  'Coming soon: Jupiter and its Icy Moons',
  'DPS-EPSC Joint Meeting, 16-21 October 2016',
  'Jupiter blasted by 6.5 fireball impacts per year on average' ]
*/


tryout({ uri: uri });
/*
expected output:
10
[ 'ESOF 2016 – What do you think a comet smells like?',
  'Juno public event: Tuesday, 5 July 2016, Athens',
  'Liquid water in Ceres’s past',
  'Counting Down to Jupiter',
  'Mission Juno : University of Liège goes into orbit at Jupiter',
  'European involvement in the Juno mission',
  'Scientists come to Schloss Seggau to discuss Rosetta’s comet',
  'Coming soon: Jupiter and its Icy Moons',
  'DPS-EPSC Joint Meeting, 16-21 October 2016',
  'Jupiter blasted by 6.5 fireball impacts per year on average' ]
*/

tryout(uri);
/*
expected output:
10
[ 'ESOF 2016 – What do you think a comet smells like?',
  'Juno public event: Tuesday, 5 July 2016, Athens',
  'Liquid water in Ceres’s past',
  'Counting Down to Jupiter',
  'Mission Juno : University of Liège goes into orbit at Jupiter',
  'European involvement in the Juno mission',
  'Scientists come to Schloss Seggau to discuss Rosetta’s comet',
  'Coming soon: Jupiter and its Icy Moons',
  'DPS-EPSC Joint Meeting, 16-21 October 2016',
  'Jupiter blasted by 6.5 fireball impacts per year on average' ]
*/
```

About the [node-feedparser](https://github.com/danmactough/node-feedparser), on the [documentation](https://github.com/danmactough/node-feedparser/tree/master#options) it sats that they still have support to the options on their constructor.

Apologize if I got something wrong, but it seems to me that your code will work just fine if you start using `FeedParser.parse(options)`.

Many thanks to bring this up again, and please let me know if we're on the same page on this.

**Comment by dsl101** [comment]
Hmm. I'm referring to feedparser-promised, and I'm using `parse()` - code extract:

```
var FeedParser = require('feedparser-promised');
promises.push(FeedParser.parse({
    uri: feedURL,
    timeout: parseInt(app.locals.feedData.config.feedTimeout),
    addmeta: false,
    dateAsString: true
}).then((items) => {
```

and since updating feedparser-promised, those options weren't (apparently) being passed through to the underlying node-feedparser. By changing the instantiation I mentioned in the original ticket _in the feedparser-promised library, not my own code_, the problem went away. Perhaps that was just working around not using it properly?

**Comment by alabeduarte** [comment]
Good news it's working!

> By changing the instantiation I mentioned in the original ticket in the feedparser-promised library, not my own code, the problem went away. Perhaps that was just working around not using it properly?

Could you elaborate more, I didn't follow. Could you show me where exactly you changed the instantiation in the `feedparser-promised` library?

Thanks!

**Comment by dsl101** [comment]
In the 'built' version (/lib/feeParserPromised.js), I changed line 31 to read:

```
var feedparser = new _feedparser2['default'](options);
```

I don't know why this worked, as I can see the `options` object is passed in to the `get()` method on line 47. But it certainly seemed to work around the problem.

I guess it's probably not directly related to this, and I'm afraid I've been looking at something else for a few days now. But I'm about to start a new project which will use feedparser-promised, so I will use the unchanged version and see if I can track it down. Unless you can see anything obvious from this update, I would suggest waiting until I have chance to explore it more. I will post back if I discover anything.

**Comment by alabeduarte** [comment]
Cool, please let me know if you need a specific behaviour or you can send a pull request with the changes.

Closing the ticket for now.

Many thanks!
