### ISSUE TITLE
"use strict";

### ISSUE THREAD

**Issue by eskan** [alabeduarte/feedparser-promised#8]
Hi,
i guess it's because i use a node old version : v4.7.3 i get this error :
```
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```
may you add "use strict"; to feedParserPromised.js ?
Thanks in advance

**Comment by alabeduarte** [comment]
Hi @eskan 

Thank you for the feedback, I'll do my best to take a look and fix it.

I'll try out with different node versions here and I'll let you know so then you can test it as well. If you feel comfortable to make a change please don't hesitate to send a pull request as well.

Best!

**Comment by alabeduarte** [comment]
Hi @eskan 

I just managed to fix it, please let me know if everything is working as expected now. I'm closing this issue for now.

Thanks!!

**Comment by eskan** [comment]
Awesome ! everything work as expected... thanks
