### ISSUE TITLE
encoding problems

### ISSUE THREAD

**Issue by adantoscano** [alabeduarte/feedparser-promised#9]
I'm working with Spanish feeds and I always get � char with special character. I tried with a decoder but I always get the same char so I think is an internal issue.

Any idea?

**Comment by alabeduarte** [comment]
Hi @AdanTL 

Do you have an example?
Just the feed url with your code snippet would help

Thanks!

**Comment by alabeduarte** [comment]
I just saw that you asked a question directly on [feedparser](https://github.com/danmactough/node-feedparser/issues/96) repository. Hopefully the answer would soulve the problem.

Please, feel free to send a pull request if you like.

**Comment by adantoscano** [comment]
>const options = {
  uri: 'http://www.sport.es/es/rss/last_news/rss_msn.xml',
  timeout: 3000
} 
feedparser.parse(options).then( (items) => {
    items.forEach( (item) => {
      console.log(item.summary);
    });
  }).catch( (error) => {
    console.log('error: ', error);
  });

Here's my feed and code. I tried the feedparser solution but they use `iconv-lite` and that only change all � char for the same, not the right one.

**Comment by alabeduarte** [comment]
Yeah, I looked at `incov-lite` as well.

```javascript
const feedparser = require('feedparser-promised');
const iconv = require('iconv-lite');

const options = {
  uri: 'http://www.sport.es/es/rss/last_news/rss_msn.xml',
  timeout: 3000
}

feedparser.parse(options).then( (items) => {
  items.forEach( (item) => {
    const encodedSummary = iconv.decode(new Buffer(item.summary), 'iso-8859-1');
    console.log(encodedSummary);
  });
}).catch( (error) => {
  console.log('error: ', error);
});
```

I'll research a little bit more

**Comment by adantoscano** [comment]
That code for example, convert � to ï¿½. Maybe we have to use incov-lite inside feedparser module

**Comment by alabeduarte** [comment]
Hi @AdanTL 

Any luck with the encoding issue? Have you talked with [feedparser](https://github.com/danmactough/node-feedparser) contributors about use incov-lite inside of it?

**Comment by alabeduarte** [comment]
Hey @AdanTL 

Any updates on your investigations? I was wondering to close this issue since it seems is not an issue with feedparser-promised. If we find something that we could do or even update with the new version of node parser we could open it again, what do you think? 

I'll close it but let me know if you think differently then I will be happy to open it again. 

Cheers
